name: Build Android (Debug APK)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-android:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Set up Java 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: System deps
        run: |
          sudo apt-get update
          sudo apt-get install -y zip unzip libssl-dev libffi-dev build-essential

      - name: Install buildozer & deps
        run: |
          python -m pip install --upgrade pip
          python -m pip install buildozer cython
          python -m pip install kivy httpx plyer

      - name: Build APK (debug)
        run: |
          buildozer android debug
        working-directory: .

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: neoncripto-apk
          path: bin/*.apk
